repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 24.8.0
- hooks:
  - id: flake8
  repo: https://github.com/pycqa/flake8
  rev: 7.1.1
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.29.0
